env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

sudo: false
language: ruby
cache: bundler

before_install:
  - gem update bundler
  
before_script:
  - bundle update

script:
  - bundle exec rspec

rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-9.0.5.0
  - ruby-head

gemfile:
  - gemfiles/rack_1.gemfile
  - gemfiles/rack_2.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head

  fast_finish: true

  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/rack_2.gemfile
